// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package sentry_common_service

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const TSENTRY_SERVICE_V1 = 1
const TSENTRY_SERVICE_V2 = 2
const TSENTRY_STATUS_OK = 0
const TSENTRY_STATUS_ALREADY_EXISTS = 1
const TSENTRY_STATUS_NO_SUCH_OBJECT = 2
const TSENTRY_STATUS_RUNTIME_ERROR = 3
const TSENTRY_STATUS_INVALID_INPUT = 4
const TSENTRY_STATUS_ACCESS_DENIED = 5
const TSENTRY_STATUS_THRIFT_VERSION_MISMATCH = 6

func init() {
}
